-- MySQL Script generated by MySQL Workbench
-- Thu Apr  3 11:35:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema db_caparao_conecta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_caparao_conecta` DEFAULT CHARACTER SET utf8 ;
USE `db_caparao_conecta` ;

-- -----------------------------------------------------
-- Table `db_caparao_conecta`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_caparao_conecta`.`pessoas` (
  `id_pessoas` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `sobre` TEXT NULL,
  `imagem` VARCHAR(255) NULL,
  PRIMARY KEY (`id_pessoas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_caparao_conecta`.`pessoasFisicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_caparao_conecta`.`pessoasFisicas` (
  `id_pessoas` INT NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `data_de_nascimento` DATE NOT NULL,
  `sobrenome` VARCHAR(255) NOT NULL,
  `cad_unico` VARCHAR(12) NULL,
  `genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pessoas`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `cad_unico_UNIQUE` (`cad_unico` ASC) VISIBLE,
  CONSTRAINT `fk_candidato_usuario`
    FOREIGN KEY (`id_pessoas`)
    REFERENCES `db_caparao_conecta`.`pessoas` (`id_pessoas`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_caparao_conecta`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_caparao_conecta`.`empresas` (
  `cnpj` VARCHAR(14) NOT NULL,
  `id_pessoas` INT NOT NULL,
  PRIMARY KEY (`id_pessoas`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  INDEX `fk_empresa_pessoa1_idx` (`id_pessoas` ASC) VISIBLE,
  CONSTRAINT `fk_empresa_pessoa1`
    FOREIGN KEY (`id_pessoas`)
    REFERENCES `db_caparao_conecta`.`pessoas` (`id_pessoas`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_caparao_conecta`.`vagas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_caparao_conecta`.`vagas` (
  `id_vagas` INT NOT NULL AUTO_INCREMENT,
  `titulo_vaga` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `salario` DECIMAL(9,2) NOT NULL,
  `status` VARCHAR(255) NULL,
  `data_criacao` DATE NOT NULL,
  `data_fechamento` DATE NOT NULL,
  `qtd_vaga` INT NOT NULL,
  `qtd_vagas_preenchidas` INT NULL,
  `modalidade_da_vaga` VARCHAR(255) NOT NULL,
  `id_empresas` INT NOT NULL,
  PRIMARY KEY (`id_vagas`),
  INDEX `fk_vagas_empresa1_idx` (`id_empresas` ASC) VISIBLE,
  CONSTRAINT `fk_vagas_empresa1`
    FOREIGN KEY (`id_empresas`)
    REFERENCES `db_caparao_conecta`.`empresas` (`id_pessoas`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_caparao_conecta`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_caparao_conecta`.`pais` (
  `id_pais` INT NOT NULL AUTO_INCREMENT,
  `nome_pais` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_pais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_caparao_conecta`.`cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_caparao_conecta`.`cidades` (
  `id_cidades` INT NOT NULL AUTO_INCREMENT,
  `nome_cidade` VARCHAR(50) NOT NULL,
  `id_pais` INT NOT NULL,
  PRIMARY KEY (`id_cidades`),
  INDEX `fk_Cidade_Pais1_idx` (`id_pais` ASC) VISIBLE,
  CONSTRAINT `fk_Cidade_Pais`
    FOREIGN KEY (`id_pais`)
    REFERENCES `db_caparao_conecta`.`pais` (`id_pais`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_caparao_conecta`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_caparao_conecta`.`enderecos` (
  `id_enderecos` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(10) NOT NULL,
  `id_cidades` INT NOT NULL,
  `bairro` VARCHAR(255) NULL,
  `endereco` VARCHAR(255) NULL,
  `id_pessoas` INT NOT NULL,
  `estado` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_enderecos`),
  INDEX `fk_Endereco_Cidade1_idx` (`id_cidades` ASC) VISIBLE,
  INDEX `fk_endereco_pessoa1_idx` (`id_pessoas` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_Cidade`
    FOREIGN KEY (`id_cidades`)
    REFERENCES `db_caparao_conecta`.`cidades` (`id_cidades`)
    ON DELETE cascade
    ON UPDATE cascade,
  CONSTRAINT `fk_endereco_pessoa1`
    FOREIGN KEY (`id_pessoas`)
    REFERENCES `db_caparao_conecta`.`pessoas` (`id_pessoas`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_caparao_conecta`.`experiencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_caparao_conecta`.`experiencias` (
  `id_experiencias` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(255) NOT NULL,
  `nome_empresa` VARCHAR(255) NOT NULL,
  `comprovacao` TINYINT NOT NULL,
  `descricao` TEXT NULL,
  `id_pessoasFisicas` INT NOT NULL,
  PRIMARY KEY (`id_experiencias`),
  INDEX `fk_Experiencias_Candidato1_idx` (`id_pessoasFisicas` ASC) VISIBLE,
  CONSTRAINT `fk_Experiencias_Candidato`
    FOREIGN KEY (`id_pessoasFisicas`)
    REFERENCES `db_caparao_conecta`.`pessoasFisicas` (`id_pessoas`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_caparao_conecta`.`instituicoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_caparao_conecta`.`instituicoes` (
  `id_instituicoes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `id_cidades` INT NOT NULL,
  PRIMARY KEY (`id_instituicoes`),
  INDEX `fk_instituicao_cidade1_idx` (`id_cidades` ASC) VISIBLE,
  CONSTRAINT `fk_instituicao_cidade1`
    FOREIGN KEY (`id_cidades`)
    REFERENCES `db_caparao_conecta`.`cidades` (`id_cidades`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_caparao_conecta`.`formacoes_academicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_caparao_conecta`.`formacoes_academicas` (
  `id_formacoes_academicas` INT NOT NULL AUTO_INCREMENT,
  `escolaridade` VARCHAR(255) NOT NULL,
  `area_de_estudo` VARCHAR(255) NULL,
  `diploma_formacao` TINYINT NOT NULL,
  `conclusao_formacao` TINYINT NOT NULL,
  `data_emissao` DATE NOT NULL,
  `data_conclusao` DATE NOT NULL,
  `id_pessoasFisicas` INT NOT NULL,
  `id_instituicoes` INT NOT NULL,
  PRIMARY KEY (`id_formacoes_academicas`),
  INDEX `fk_Formacao_academica_Candidato1_idx` (`id_pessoasFisicas` ASC) VISIBLE,
  INDEX `fk_formacao_academica_instituicao1_idx` (`id_instituicoes` ASC) VISIBLE,
  CONSTRAINT `fk_Formacao_academica_Candidato1`
    FOREIGN KEY (`id_pessoasFisicas`)
    REFERENCES `db_caparao_conecta`.`pessoasFisicas` (`id_pessoas`)
    ON DELETE cascade
    ON UPDATE cascade,
  CONSTRAINT `fk_formacao_academica_instituicao1`
    FOREIGN KEY (`id_instituicoes`)
    REFERENCES `db_caparao_conecta`.`instituicoes` (`id_instituicoes`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_caparao_conecta`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_caparao_conecta`.`cursos` (
  `id_cursos` INT NOT NULL AUTO_INCREMENT,
  `curso` VARCHAR(255) NOT NULL,
  `organizacao_emissora` VARCHAR(255) NOT NULL,
  `cargo_horaria` VARCHAR(50) NOT NULL,
  `certificado_curso` TINYINT NOT NULL,
  `data_conclusao` DATE NOT NULL,
  `tipo_de_curso` VARCHAR(255) NULL,
  PRIMARY KEY (`id_cursos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_caparao_conecta`.`habilidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_caparao_conecta`.`habilidades` (
  `id_habilidades` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id_habilidades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_caparao_conecta`.`candidaturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_caparao_conecta`.`candidaturas` (
  `id_vagas` INT NOT NULL,
  `id_pessoasFisicas` INT NOT NULL,
  `data_candidatura` DATE NOT NULL,
  PRIMARY KEY (`id_vagas`, `id_pessoasFisicas`),
  INDEX `fk_vagas_has_candidato_candidato1_idx` (`id_pessoasFisicas` ASC) VISIBLE,
  INDEX `fk_vagas_has_candidato_vagas1_idx` (`id_vagas` ASC) VISIBLE,
  CONSTRAINT `fk_vagas_candidato`
    FOREIGN KEY (`id_vagas`)
    REFERENCES `db_caparao_conecta`.`vagas` (`id_vagas`)
    ON DELETE cascade
    ON UPDATE cascade,
  CONSTRAINT `fk_candidato_vaga`
    FOREIGN KEY (`id_pessoasFisicas`)
    REFERENCES `db_caparao_conecta`.`pessoasFisicas` (`id_pessoas`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_caparao_conecta`.`redesSociais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_caparao_conecta`.`redesSociais` (
  `intagram` VARCHAR(255) NULL,
  `github` VARCHAR(255) NULL,
  `linkedin` VARCHAR(255) NULL,
  `curriculo_lattes` VARCHAR(255) NULL,
  `id_redeSociais` INT NOT NULL AUTO_INCREMENT,
  `id_pessoas` INT NOT NULL,
  PRIMARY KEY (`id_redeSociais`, `id_pessoas`),
  INDEX `fk_redesSociais_pessoa1_idx` (`id_pessoas` ASC) VISIBLE,
  CONSTRAINT `fk_redesSociais_pessoa1`
    FOREIGN KEY (`id_pessoas`)
    REFERENCES `db_caparao_conecta`.`pessoas` (`id_pessoas`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_caparao_conecta`.`tipo_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_caparao_conecta`.`tipo_usuarios` (
  `id_tipo_usuarios` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_usuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_caparao_conecta`.`vagas_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_caparao_conecta`.`vagas_cursos` (
  `id_cursos` INT NOT NULL,
  `id_vagas` INT NOT NULL,
  PRIMARY KEY (`id_cursos`, `id_vagas`),
  INDEX `fk_cursos_profissionalizantes_has_vagas_vagas1_idx` (`id_vagas` ASC) VISIBLE,
  INDEX `fk_cursos_profissionalizantes_has_vagas_cursos_profissional_idx` (`id_cursos` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_profissionalizantes_has_vagas_cursos_profissionaliz1`
    FOREIGN KEY (`id_cursos`)
    REFERENCES `db_caparao_conecta`.`cursos` (`id_cursos`)
    ON DELETE cascade
    ON UPDATE cascade,
  CONSTRAINT `fk_cursos_profissionalizantes_has_vagas_vagas1`
    FOREIGN KEY (`id_vagas`)
    REFERENCES `db_caparao_conecta`.`vagas` (`id_vagas`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_caparao_conecta`.`vagas_habilidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_caparao_conecta`.`vagas_habilidades` (
  `id_habilidades` INT NOT NULL,
  `id_vagas` INT NOT NULL,
  PRIMARY KEY (`id_habilidades`, `id_vagas`),
  INDEX `fk_habilidades_has_vagas_vagas1_idx` (`id_vagas` ASC) VISIBLE,
  INDEX `fk_habilidades_has_vagas_habilidades1_idx` (`id_habilidades` ASC) VISIBLE,
  CONSTRAINT `fk_habilidades_has_vagas_habilidades1`
    FOREIGN KEY (`id_habilidades`)
    REFERENCES `db_caparao_conecta`.`habilidades` (`id_habilidades`)
    ON DELETE cascade
    ON UPDATE cascade,
  CONSTRAINT `fk_habilidades_has_vagas_vagas1`
    FOREIGN KEY (`id_vagas`)
    REFERENCES `db_caparao_conecta`.`vagas` (`id_vagas`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_caparao_conecta`.`pessoasFisicas_habilidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_caparao_conecta`.`pessoasFisicas_habilidades` (
  `id_pessoasFisicas` INT NOT NULL,
  `id_habilidades` INT NOT NULL,
  PRIMARY KEY (`id_pessoasFisicas`, `id_habilidades`),
  INDEX `fk_candidato_has_habilidades_habilidades1_idx` (`id_habilidades` ASC) VISIBLE,
  INDEX `fk_candidato_has_habilidades_candidato1_idx` (`id_pessoasFisicas` ASC) VISIBLE,
  CONSTRAINT `fk_candidato_has_habilidades_candidato1`
    FOREIGN KEY (`id_pessoasFisicas`)
    REFERENCES `db_caparao_conecta`.`pessoasFisicas` (`id_pessoas`)
    ON DELETE cascade
    ON UPDATE cascade,
  CONSTRAINT `fk_candidato_has_habilidades_habilidades1`
    FOREIGN KEY (`id_habilidades`)
    REFERENCES `db_caparao_conecta`.`habilidades` (`id_habilidades`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_caparao_conecta`.`pessoasFisicas_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_caparao_conecta`.`pessoasFisicas_cursos` (
  `id_cursos` INT NOT NULL,
  `id_pessoasFisicas` INT NOT NULL,
  PRIMARY KEY (`id_cursos`, `id_pessoasFisicas`),
  INDEX `fk_cursos_has_candidato_candidato1_idx` (`id_pessoasFisicas` ASC) VISIBLE,
  INDEX `fk_cursos_has_candidato_cursos1_idx` (`id_cursos` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_has_candidato_cursos1`
    FOREIGN KEY (`id_cursos`)
    REFERENCES `db_caparao_conecta`.`cursos` (`id_cursos`)
    ON DELETE cascade
    ON UPDATE cascade,
  CONSTRAINT `fk_cursos_has_candidato_candidato1`
    FOREIGN KEY (`id_pessoasFisicas`)
    REFERENCES `db_caparao_conecta`.`pessoasFisicas` (`id_pessoas`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_caparao_conecta`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_caparao_conecta`.`usuarios` (
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(512) NOT NULL,
  `id_tipo_usuarios` INT NOT NULL,
  `id_pessoas` INT NOT NULL,
  INDEX `fk_usuario_tipo_usuario1_idx` (`id_tipo_usuarios` ASC) VISIBLE,
  PRIMARY KEY (`id_pessoas`),
  CONSTRAINT `fk_usuario_tipo_usuario1`
    FOREIGN KEY (`id_tipo_usuarios`)
    REFERENCES `db_caparao_conecta`.`tipo_usuarios` (`id_tipo_usuarios`)
    ON DELETE cascade
    ON UPDATE cascade,
  CONSTRAINT `fk_usuario_pessoa1`
    FOREIGN KEY (`id_pessoas`)
    REFERENCES `db_caparao_conecta`.`pessoas` (`id_pessoas`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;

